### ISSUE TITLE
Container dying with "Exit code 137"

### ISSUE THREAD

**Issue by fniko** [quickbreach/PowerShell-NTLM#2]
Hello,
I have discovered, the container is dying when I run more than 3 / 4 jobs on Azure Devops Pipelines.
The error:
```
##[error]Exit code 137 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1000 7c1f2aba43d11da135e5861ccb3f457971dfcb1c0bbe033f5cb1fb5956845211 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
```
It seems like it could be OOM error, however the host have 8 GB of RAM and only about ~1.2 GB was consumed before the crash.

I am using self-hosted agent, details:
**Host OS**: Ubuntu 18.04.4 LTS

Full log from Azure Pipelines:
https://pastebin.com/E4dPcxSx

Code:
```
      - deployment: uploadToServer
        dependsOn: PrepareENV
        container: quickbreach/powershell-ntlm:latest
        displayName: Upload and restart
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPackage@1
                  displayName: 'Download package from feed'
                  inputs:
                    packageType: upack
                    feed: 'aaaa-bbbb-cccc'
                    definition: 'offline-page'
                    version: '1.0.28'
                    downloadPath: '$(System.ArtifactsDirectory)'
                    extract: false
```

Is there some way how to troubleshoot this further?
Or is this too Azure Devops Pipeline related so I should contant Microsoft in this case?

> I also tried using the base image: mcr.microsoft.com/powershell:latest, but since there is not native support for NTLM (what I need), I dediced to go with your image instead.
